apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: aggregate-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "aggregate sink"
    description: |-
      Aggregate multiple messages to one message
    type: object
    properties:
      aggregateType:
          title: Aggregate Type
          description: Aggregate Type
          type: string
          default: "text/xml"
      completionSize:
          title: Completion Size
          description: Completion Size
          type: string
          default: 3
      completionTimeout:
        title: Completion Timeout
        description: Completion Timeout in milliseconds
        type: string
      completionInterval:
        title: Completion Interval
        description: Completion Interval in milliseconds
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setProperty:
              name: Aggregate-Type
              constant: "{{aggregateType}}"
          - aggregate:
              aggregationStrategy: "AggregateStrategy"
              completionSize: "{{completionSize}}"
              completionTimeout: "{{?completionTimeout}}"
              completionInterval: "{{?completionInterval}}"
              correlationExpression:
                constant: "true"
          - to:
              uri: "mock:result"