apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: aggregate-router
  labels:
    camel.apache.org/kamelet.type: "router"
spec:
  definition:
    title: "aggregate router"
    description: |-
      to do
    type: object
    properties:
      aggregateType:
          title: Aggregate Type
          description: Aggregate Type
          type: string
          default: "text/xml"
      completionSize:
          title: Completion Size
          description: Completion Size
          type: string
          default: 3
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setProperty:
              name: Aggregate-Type
              constant: "{{aggregateType}}"
          - aggregate:
              aggregationStrategy: "AggregateStrategy"
              completionSize: "{{completionSize}}"
              correlationExpression:
                constant: "true"
          - to:
              uri: "kamelet:sink"