apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: amazon-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "amazon action"
    description: |-
      Amazon component
    type: object
    properties:
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "amazon:{{path}}?{{options}}"
          - to:
              uri: "kamelet:sink"