apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: appendtobody-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "appendtobody action"
    description: |-
      Append text to a message body
    type: object
    properties:
      path:
        title: Path
        description: Path
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - transform:
              method: body().append("{{path}}")