apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "appendtobody-sink"
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "appendtobody action"
    description: "Append text to a message body"
    type: "object"
    properties:
      path:
        title: "Path"
        description: "Path"
        type: "string"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeId:
        title: "Route ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
  dependencies:
  - "camel:kamelet"
  template:
    route:
      from:
        uri: "{{in}}"
        steps:
        - step:
            id: "{{routeId}}"
            steps:
            - transform:
                method: "body().append(\"{{path}}\")"
      routeConfigurationId: "{{routeConfigurationId}}"
