apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "as2-source"
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "as2 source"
    description: "AS2 endpoint that accepts and processes inbound AS2 transmissions"
    type: "object"
    properties:
      serverPortNumber:
        title: ServerPortNumber
        description: ServerPortNumber
        type: string
        default: "9002"
      requestUriPattern:
        title: RequestUriPattern
        description: RequestUriPattern
        type: string
      as2From:
        title: As2From
        description: As2From
        type: string
      as2To:
        title: As2To
        description: As2To
        type: string
      serverFqdn:
        title: ServerFqdn
        description: ServerFqdn
        type: string
      as2MessageStructure:
        title: As2MessageStructure
        description: As2MessageStructure
        type: string
      signingPrivateKey:
        title: SigningPrivateKey
        description: signingPrivateKey
        type: string
      decryptingPrivateKey:
        title: DecryptingPrivateKey
        description: DecryptingPrivateKey
        type: string
      signingCertificateChain:
        title: SigningCertificateChain
        description: SigningCertificateChain
        type: string
      validateSigningCertificateChain:
        title: ValidateSigningCertificateChain
        description: ValidateSigningCertificateChain
        type: string
      options:
        title: "options (query parameters)"
        description: "Endpoint URI"
        type: "string"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeId:
        title: "Route ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
  dependencies:
  - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeConfigurationId}}"
      from:
        uri: >-
          as2://server/listen?serverPortNumber={{serverPortNumber}}
          &requestUriPattern={{requestUriPattern}}
          &as2From={{as2From}}
          &as2To={{as2To}}
          &serverFqdn={{serverFqdn}}
          &as2MessageStructure={{as2MessageStructure}}
          &signingPrivateKey=RAW({{?signingPrivateKey}})
          &decryptingPrivateKey=RAW({{?decryptingPrivateKey}})
          &signingCertificateChain=RAW({{?signingCertificateChain}})
          &validateSigningCertificateChain=RAW({{?validateSigningCertificateChain}})
        steps:
        - step:
            id: "{{routeId}}"
            steps:
            - to:
                uri: "{{out}}"
