apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "as2-action"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "as2 action"
    description: "Sends documents to a partner using the AS2 protocol"
    type: "object"
    properties:
      hostName:
        title: HostName
        description: HostName
        type: "string"
      targetPortNumber:
        title: TargetPortNumber
        description: TargetPortNumber
        type: "string"
      requestUri:
        title: RequestUri
        description: RequestUri
        type: string
      as2From:
        title: As2From
        description: As2From
        type: string
      as2To:
        title: As2To
        description: As2To
        type: string
      subject:
        title: Subject
        description: Subject
        type: string
      as2MessageStructure:
        title: As2MessageStructure
        description: As2MessageStructure
        type: "string"
      ediMessageContentType:
        title: EdiMessageContentType
        description: EdiMessageContentType
        type: "string"
      encryptingAlgorithm:
        title: EncryptingAlgorithm
        description: EncryptingAlgorithm
        type: "string"
      signingAlgorithm:
        title: SigningAlgorithm
        description: SigningAlgorithm
        type: "string"
      sslContext:
        title: SslContext
        description: SslContext
        type: "string"
      password:
        title: Password
        description: Password
        type: "string"
        x-descriptors:
          - "urn:camel:group:credentials"
      alias:
        title: Alias
        description: Alias
        type: "string"
      certificateForSigning:
        title: CertificateForSigning
        description: CertificateForSigning
        type: "string"
      certificateForEncrypt:
        title: CertificateForEncrypt
        description: CertificateForEncrypt
        type: "string"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeId:
        title: "Route ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
  dependencies:
  - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeConfigurationId}}"
      from:
        uri: "{{in}}"
        steps:
        - step:
            id: "{{routeId}}"
            steps:
            - setProperty:
                name: "messageStructure"
                constant: "{{as2MessageStructure}}"
            - setProperty:
                name: "keyPassword"
                constant: "{{password}}"
            - setProperty:
                name: "keyAlias"
                constant: "{{alias}}"
            - setProperty:
                name: "certificateForSigning"
                constant: "{{certificateForSigning}}"
            - setProperty:
                name: "certificateForEncrypt"
                constant: "{{certificateForEncrypt}}"
            - process:
                ref: "AS2KeyProcessor"
            - to:
                uri: >-
                  as2://client/send?inBody=ediMessage
                  &targetHostname={{hostName}}
                  &targetPortNumber={{targetPortNumber}}
                  &requestUri={{requestUri}}
                  &as2From={{as2From}}
                  &as2To={{as2To}}
                  &subject=RAW({{subject}})
                  &from={{as2From}}
                  &dispositionNotificationTo=test
                  &as2MessageStructure={{as2MessageStructure}}
                  &ediMessageContentType={{ediMessageContentType}}
                  &methodName=send&encryptingAlgorithm={{encryptingAlgorithm}}
                  &signingAlgorithm={{signingAlgorithm}}
                  &exchangePattern=InOut
                  &sslContext={{?sslContext}}
                  &hostnameVerifier=#permissiveHostnameVerifier
            - process:
                ref: "AS2MDNProcessor"
            - to:
                uri: "{{out}}"

