apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "base64totext-sink"
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "base64totext sink"
    description: "Convert a body in base64 encoding to plain text"
    type: "object"
    properties:
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeId:
        title: "Route ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
  dependencies:
  - "camel:kamelet"
  template:
    route:
      from:
        uri: "{{in}}"
        steps:
        - step:
            id: "{{routeId}}"
            steps:
            - unmarshal:
                base64: {}
      routeConfigurationId: "{{routeConfigurationId}}"
