apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: base64totext-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "base64totext action"
    description: |-
      to do
    type: object
    properties:
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - unmarshal:
              base64: {}
          - to:
              uri: "kamelet:sink"