apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: connect-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "connect sink"
    description: |-
      to do
    type: object
    properties:
      path:
        title: Path
        description: Path
        type: string
      options:
        title: Options
        description: Endpoint options
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "rest:connect:{{path}}?{{options}}"