apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: delay-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "Delay Action"
    description: Delay the processing using a specific amount of time
    type: object
    properties:
      milliseconds:
        title: "Milliseconds"
        description: "The number of milliseconds of delay"
        type: "integer"
        default: 5000
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
  dependencies:
    - "camel:core"
    - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeConfigurationId}}"
      from:
        uri: "kamelet:source"
        steps:
          - step:
              id: "{{routeId}}"
              steps:
                - delay:
                  constant: "{{milliseconds}}"
                - to:
                  uri: "{{out}}"
