apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: docconverter-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "DocConverter Action"
    description: |-
      Convert between various formats (XML, JSON, YAML and CSV)
    type: object
    properties:
      path:
        title: Path
        description: Path
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "docconverter:{{path}}"
          - to:
              uri: "kamelet:sink"