apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "docconverter-action"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "DocConverter Action"
    description: "Convert between various formats (XML, JSON, YAML and CSV)"
    type: "object"
    properties:
      convert:
        title: "Convert"
        description: "Convert dataformat to another"
        type: "string"
        default: "xmltojson"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeId:
        title: "Route ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
  dependencies:
  - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeConfigurationId}}"
      from:
        uri: "{{in}}"
        steps:
        - step:
            id: "{{routeId}}"
            steps:
            - to:
                uri: "docconverter:{{convert}}"
            - to:
                uri: "{{out}}"
