apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: dynamic-router
  labels:
    camel.apache.org/kamelet.type: "router"
spec:
  definition:
    title: "dynamic router"
    description: |-
      Dynamic route message to on or more addresses
    type: object
    properties:
      out_rules_list:
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setProperty:
              name: routingRules
              constant: "{{path}}"
          - setProperty:
              name: defaultEndpoint
              constant: "{{out}}"
          - process:
              ref: "RoutingRulesProcessor"
          - toD:
              uri: "${exchangeProperty.endpoint}"