apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "dynamic-router"
  labels:
    camel.apache.org/kamelet.type: "router"
spec:
  definition:
    title: "Dynamic router"
    description: "Content-based router to route messages to one or more addresses.\n\
      Note: this Kamelet is an alternative for the content-router that is generated\
      \ as a normal route, instead of a Kamelet"
    type: "object"
    properties:
      out_rules_list:
        type: "string"
      out_default:
        type: "string"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeId:
        title: "Route ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
  dependencies:
  - "camel:kamelet"
  template:
    route:
      from:
        uri: "{{in}}"
        steps:
        - step:
            id: "{{routeId}}"
            steps:
            - setProperty:
                name: "routingRules"
                constant: "{{out_rules_list}}"
            - setProperty:
                name: "defaultEndpoint"
                constant: "{{out_default}}"
            - process:
                ref: "RoutingRulesProcessor"
            - toD:
                uri: "${exchangeProperty.endpoint}"
      routeConfigurationId: "{{routeConfigurationId}}"
