apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: dynamic-router
  labels:
    camel.apache.org/kamelet.type: "router"
spec:
  definition:
    title: "Dynamic router"
    description: |-
      Content-based router to route messages to one or more addresses.
      Note: this Kamelet is an alternative for the content-router that is generated as a normal route, instead of a Kamelet
    type: object
    properties:
      out_rules_list:
        type: string
      out_default:
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setProperty:
              name: routingRules
              constant: "{{out_rules_list}}"
          - setProperty:
              name: defaultEndpoint
              constant: "{{out_default}}"
          - process:
              ref: "RoutingRulesProcessor"
          - toD:
              uri: "${exchangeProperty.endpoint}"