apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: edifactstandardstoxml-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "edifactstandardstoxml sink"
    description: |-
      Convert Edifact Standards to XML
    type: object
    properties:
      path:
        title: Path
        description: Path
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "edifact-standards:{{path}}"