apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: edifacttoxml-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "edifacttoxml action"
    description: |-
      Converts Edifact to XML
    type: object
    properties:
      options:
          title: Options
          description: Options
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "dataformat:edifact:marshal?{{options}}"
          - to:
              uri: "kamelet:sink"