apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: elasticsearch-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "ElasticSearch Sink"
    description: Stores JSON-formatted data into ElasticSearch.
    required:
      - clusterName
      - hostAddresses
    type: object
    properties:
      user:
        title: Username
        description: The username to connect to ElasticSearch.
        type: string
        x-descriptors:
        - urn:camel:group:credentials
      password:
        title: Password
        description: The password to connect to ElasticSearch.
        type: string
        format: password
        x-descriptors:
        - urn:camel:group:credentials
      enableSSL:
        title: Enable SSL
        description: Specifies to connect by using SSL.
        type: boolean
        default: true
      hostAddresses:
        title: Host Addresses
        description: A comma-separated list of remote transport addresses in `ip:port format`.
        type: string
        example: quickstart-es-http:9200
      clusterName:
        title: ElasticSearch Cluster Name
        description: The name of the ElasticSearch cluster.
        type: string
        example: quickstart
      indexName:
        title: Index in ElasticSearch
        description: The name of the ElasticSearch index.
        type: string
        example: data
      certificate:
        title: Certificate 
        description: The Certificate for accessing the Elasticsearch cluster. You must encode this value in base64.
        type: string
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeId:
        title: "Route ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"        
  types:
    out:
      mediaType: text/plain
    in:
      mediaType: application/json
  dependencies:
    - "camel:core"
    - "camel:jackson"
    - "camel:kamelet"
    - "camel:elasticsearch"
    - "camel:gson"
    - "camel:bean"
  template:
    beans:
      - name: local-es
        type: "#class:org.apache.camel.component.es.ElasticsearchComponent"
        properties:
            user: "{{?user}}"
            password: "{{?password}}"
    route:
      routeConfigurationId: "{{routeConfigurationId}}"
      from:
        uri: "{{in}}"
        steps:
        - step:
            id: "{{routeId}}"
            steps:        
            - choice:
                when:
                - simple: "${header[indexId]}"
                  steps:
                  - setHeader:
                      name: "indexId"
                      simple: "${header[indexId]}"
                - simple: "${header[ce-indexid]}"
                  steps:
                  - setHeader:
                      name: "indexId"
                      simple: "${header[ce-indexid]}"
            - choice:
                when:
                - simple: "${header[indexName]}"
                  steps:
                  - setHeader:
                      name: "indexName"
                      simple: "${header[indexName]}"
                - simple: "${header[ce-indexname]}"
                  steps:
                  - setHeader:
                      name: "indexName"
                      simple: "${header[ce-indexname]}"
            - to:
                uri: "{{local-es}}:{{clusterName}}"
                parameters:
                  operation: "INDEX"
                  hostAddresses: "{{hostAddresses}}"
                  enableSSL: "{{enableSSL}}"
                  indexName: "{{?indexName}}"
                  certificatePath: "base64:{{?certificate}}"