apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: exceltoxml-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "exceltoxml sink"
    description: |-
      Convert Excel to XML
    type: object
    properties:
      options:
        title: Options
        description: Options
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "exceltoxml://?{{options}}"