apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: file-source
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "file source"
    description: |-
      File endpoint that listens to a directory
    type: object
    properties:
      path:
        title: path
        description: path of component
        type: string
        default: dummy
      options:
        title: options (query parameterS)
        description: Endpoint URI
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "file://{{path}}?bridgeErrorHandler=true&{{?options}}"
        steps:
          - to:
              uri: "kamelet:sink"