apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "file-source"
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "file source"
    description: "File endpoint that listens to a directory"
    type: "object"
    properties:
      path:
        title: "path"
        description: "path of component"
        type: "string"
        default: "dummy"
      options:
        title: "options (query parameterS)"
        description: "Endpoint URI"
        type: "string"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeId:
        title: "Route ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
  dependencies:
  - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeConfigurationId}}"
      from:
        uri: "file://{{path}}?bridgeErrorHandler=true&{{?options}}"
        steps:
        - step:
            id: "{{routeId}}"
            steps:
            - to:
                uri: "{{out}}"

