apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "filter-action"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "filter-action"
    description: "Filter message by an expression (XPath, Jsonpath or Simple)"
    type: "object"
    properties:
      expression:
        title: "Expression"
        description: "Expression"
        type: "string"
      language:
        title: "Language"
        description: "Language"
        type: "string"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeId:
        title: "Route ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
  dependencies:
  - "camel:kamelet"
  template:
    route:
      from:
        uri: "{{in}}"
        steps:
        - step:
            id: "{{routeId}}"
            steps:
            - filter:
                language:
                  language: "{{language}}"
                  expression: "{{expression}}"
            - to:
                uri: "{{out}}"
      routeConfigurationId: "{{routeConfigurationId}}"
