apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: filter-xpath-router
  labels:
    camel.apache.org/kamelet.type: "xpath-router"
spec:
  definition:
    title: "filter xpath-router"
    description: |-
      Filter message by XPath
    type: object
    properties:
      out_rule:
          title: Out Rules
          description: Out going URI
          type: string
      expression:
          title: Expression
          description: Expression
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - filter:
              xpath: "{{expression}}"
          - to:
              uri: "{{out_rule}}"