apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: filter-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "filter-sink"
    description: |-
      Filter message by an expression (XPath, Jsonpath or Simple)
    type: object
    properties:
      expression:
          title: Expression
          description: Expression
          type: string
      language:
        title: Language
        description: Language
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - filter:
              language:
                language: "{{language}}"
                expression: "{{expression}}"