apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: filter-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "filter-action"
    description: |-
      Filter message by XPath
    type: object
    properties:
      out_filter:
          title: Out Rules
          description: Out going URI
          type: string
      expression:
          title: Expression
          description: Expression
          type: string
      language:
        title: Language
        description: Language
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - filter:
              language:
                language: "{{language}}"
                expression: "{{expression}}"
          - to:
              uri: "kamelet:sink"