apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: flowlink-source
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "flowlink source"
    description: |-
      Links messages to another flow (inbound) using an endpoint like sync (direct), async (seda), activemq
    type: object
    properties:
      transport:
        title: Transport
        description: Transport
        type: string
      flowId:
        title: FlowID
        description: Flow ID of the flow
        type: string
      connectionFactory:
        title: Connection Factory
        description: Connection Factory
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "{{transport}}:{{flowId}}?connectionFactory={{?connectionFactory}}"
        steps:
          - to:
              uri: "kamelet:sink"