apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: flv-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "flv action"
    description: |-
      Transform FLV (Fixed length)
    type: object
    properties:
      routeId:
        title: routeId
        description: ID of route (flowId + stepId)
        type: string
        default: dummy
      options:
        title: options (query parameterS)
        description: Endpoint URI
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "flv:{{routeId}}?{{?options}}"
          - to:
              uri: "kamelet:sink"