apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: formtoxml-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "formtoxml action"
    description: |-
      Convert Form to XML
    type: object
    properties:
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "formtoxml://?encoding=utf-8"
          - to:
              uri: "kamelet:sink"