apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: formtoxml-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "formtoxml sink"
    description: |-
      Convert Form to XML
    type: object
    properties:
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "formtoxml://?{{options}}"
          - to:
              uri: "kamelet:sink"