apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: ftps-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "ftps sink"
    description: |-
      Sends messages to a FTPS directory
    type: object
    properties:
      path:
        title: path
        description: path of the URI
        type: string
      options:
        title: options (query parameterS)
        description: URI query parameters (Endpoint options)
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - toD:
              uri: "ftps://{{path}}?{{?options}}"