apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: ftps-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "ftps action"
    description: |-
      Send messages to a FTPS directory
    type: object
    properties:
      path:
        title: path
        description: path of component
        type: string
      options:
        title: options (query parameterS)
        description: Endpoint URI
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - toD:
              uri: "ftps:{{path}}?{{?options}}"
          - to:
              uri: "kamelet:sink"