apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: generic-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "generic sink"
    description: |-
      Generic kamelet for Camel Components
    type: object
    properties:
      uri:
        title: URI
        description: Endpoint URI
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - toD:
              uri: "{{uri}}"