apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: generic-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "generic action"
    description: |-
      Generic kamelet for Camel Components to send messages to an endpoint
    type: object
    properties:
      scheme:
        title: scheme of components
        description: Scheme of URI (normally the name of the component)
        type: string
      path:
        title: path
        description: path of the URI
        type: string
        default: dummy
      options:
        title: options (query parameters)
        description: URI query parameters (Endpoint options)
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - toD:
              uri: "{{scheme}}://{{path}}?{{?options}}"
          - to:
              uri: "kamelet:sink"