apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: generic-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "generic action"
    description: |-
      Generic kamelet for Camel Components to send messages to an endpoint
    type: object
    properties:
      scheme:
        title: scheme of components
        description: Endpoint URI
        type: string
      path:
        title: path
        description: path of component
        type: string
        default: dummy
      options:
        title: options (query parameterS)
        description: Endpoint URI
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - toD:
              uri: "{{scheme}}://{{path}}?{{?options}}"