apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: generic-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "generic action"
    description: |-
      Generic kamelet for Camel Components
    type: object
    properties:
      uri:
          title: URI
          description: Endpoint URI
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - toD:
              uri: "{{uri}}"
          - to:
              uri: "kamelet:sink"