apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: googledrive-source
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "googledrive source"
    description: |-
      Get files from GoogleDrive
    type: object
    properties:
      path:
        title: path
        description: path of the URI (directoryId)
        type: string
        default: dummy
      options:
        title: Options
        description: Options
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "googledrive://{{path}}?{{options}}"
        steps:
          - to:
              uri: "kamelet:sink"