apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: groovy-script
  labels:
    camel.apache.org/kamelet.type: "script"
spec:
  definition:
    title: "groovy script"
    description: |-
      Apply Groovy script
    type: object
    properties:
      path:
        title: Path
        description: Path
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "sandbox://groovy?script=RAW({{path}})"