apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: head-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "head action"
    description: |-
      to do
    type: object
    properties:
      path:
        title: Path
        description: Path
        type: string
      options:
        title: Options
        description: Endpoint options
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "rest:head:{{path}}?{{options}}"
          - to:
              uri: "kamelet:sink"