apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: https-source
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "https source"
    description: |-
      Receives HTTP Requests
    type: object
    properties:
      path:
        title: Path
        description: Path of the URL
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "jetty:https:{{path}}?jettyHttpBinding=#customHttpBinding&sslContextParameters=sslContext"
        steps:
          - removeHeaders:
              pattern: "CamelHttp*"
          - to:
              uri: "kamelet:sink"