apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: https-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "https sink"
    description: |-
      Sends HTTP Requests
    type: object
    properties:
      uri:
          title: URI
          description: Endpoint URI
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "{{uri}}"
