apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: http-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "http action"
    description: |-
      HTTP Action
    type: object
    properties:
      uri:
        title: URI
        description: URI
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "{{uri}}"
          - to:
              uri: "kamelet:sink"