apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: joor-script
  labels:
    camel.apache.org/kamelet.type: "script"
spec:
  definition:
    title: "joor script"
    description: |-
      Runs java code (through joor)
    type: object
    properties:
      path:
          title: Path
          description: Path
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setBody:
              joor: "{{path}}"
          - to:
              uri: "kamelet:sink"