apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: jslt-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "jslt action"
    description: |-
      to do
    type: object
    properties:
      path:
          title: Path
          description: Path
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setHeader:
              name: CamelJsltString
              constant: "{{path}}"
          - to:
              uri: "jslt:dummy?allowTemplateFromHeader=true"
          - to:
              uri: "kamelet:sink"