apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: jslt-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "jslt action"
    description: |-
      to do
    type: object
    properties:
      path:
        title: Path
        description: Path
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setHeader:
              name: CamelJsltString
              constant: "{{path}}"
          - to:
              uri: "jslt:dummy?allowTemplateFromHeader=true"