apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: jslt-script
  labels:
    camel.apache.org/kamelet.type: "script"
spec:
  definition:
    title: "jslt script"
    description: |-
      to do
    type: object
    properties:
      path:
        title: Path
        description: Path
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setHeader:
              name: CamelJsltString
              constant: "{{path}}"
          - to:
              uri: "jslt:dummy?allowTemplateFromHeader=true"
          - to:
              uri: "kamelet:sink"