apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: jsontoxml-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "jsontoxml sink"
    description: |-
      Convert JSON to XML
    type: object
    properties:
      options:
          title: Options
          description: Options
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "dataformat:custom-xmljson:unmarshal?{{options}}"
