apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "jsontoxml-sink"
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "jsontoxml sink"
    description: "Convert JSON to XML"
    type: "object"
    properties:
      options:
        title: "Options"
        description: "Options"
        type: "string"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeId:
        title: "Route ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
  dependencies:
  - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeConfigurationId}}"
      from:
        uri: "{{in}}"
        steps:
        - step:
            id: "{{routeId}}"
            steps:
            - to:
                uri: "jsontoxml:path?{{options}}"
