apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "langchain4j-chat-action"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "langchain4j-chat action"
    description: "chat component for langchain4j"
    type: "object"
    properties:
      path:
        title: "Path"
        description: "Path"
        type: "string"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeId:
        title: "Route ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
      apiKey:
        title: "API Key"
        type: "string"
        default: "AIzaSyBYU3k4uTv92cGsgYW4afJiKKu6FtRYfK0"
      modelName:
        title: "Model Name"
        type: "string"
        default: "gemini-3-flash-preview"
      prompt:
        title: "Prompt"
        type: "string"
        default: "Vertel me een leuke grap over programmeurs."
  dependencies:
    - "camel:kamelet"
  template:
    beans:
      - name: "GeminiChatModel2"
        type: "#class:org.assimbly.dil.blocks.models.GoogleAiGeminiChatModel"
        factoryMethod: "create"
    route:
      from:
        uri: "{{in}}"
        steps:
          - convertBodyTo:
              type: String
          - setHeader:
              name: "CamelLangChain4jChatPromptTemplate"
              expression:
                 constant:
                    expression: "maak een grapje"
          - to:
              uri: "log:langchain4jin?showAll=true&multiline=true"
          - to:
              uri: "langchain4j-chat://{{routeId}}?chatModel=#bean:geminiChatModel"
          - to:
              uri: "log:langchain4jout?showAll=true&multiline=true"
          - to:
              uri: "{{out}}"
