apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "langchain4j-agent-sink"
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "langchain4j-agent sink"
    description: "agent component for langchain4j"
    type: "object"
    properties:
      path:
        title: "Path"
        description: "Path"
        type: "string"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeId:
        title: "Route ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
      agent:
        title: "Agent Bean Name"
        type: "string"
        default: "#bean:GeminiAgent2"
  dependencies:
    - "camel:kamelet"
  template:
    beans:
      - name: "GeminiAgent2"
        type: "#class:org.assimbly.dil.blocks.models.GoogleAiGeminiAgent"
        factoryMethod: "create"
    route:
      routeConfigurationId: "{{routeConfigurationId}}"
      from:
        uri: "{{in}}"
        steps:
          - step:
              id: "{{routeId}}"
              steps:
                - convertBodyTo:
                    type: String
                - to:
                    uri: "langchain4j-agent://{{routeId}}?agent={{agent}}"
