apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: link-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "link action"
    description: |-
      Links steps
    type: object
    properties:
      uri:
          title: Path
          description: Path
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "kamelet:sink"
