apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: link-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "link sink"
    description: |-
      Links steps
    type: object
    properties:
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "kamelet:sink"
