apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: link-router
  labels:
    camel.apache.org/kamelet.type: "router"
spec:
  definition:
    title: "link router"
    description: |-
      Links steps
    type: object
    properties:
      out_list:
        title: Out List
        description: Out List
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - recipientList:
              constant: "{{out_list}}"
