apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: log-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "log action"
    description: |-
      Logs e message
    type: object
    properties:
      routeId:
        title: routeId
        description: path of component
        type: string
        default: dummy
      options:
        title: options (query parameterS)
        description: Endpoint URI
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - toD:
              uri: "log://{{routeId}}?{{?options}}"
          - to:
              uri: "kamelet:sink"