apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "logger-action"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "logger action"
    description: "Logs a message using simple expressions"
    type: "object"
    properties:
      routeId:
        title: "routeId"
        description: "path of component"
        type: "string"
        default: "dummy"
      language:
        title: "Language"
        description: "Set the expression language"
        type: "string"
        default: "constant"
      loggingLevel:
        title: "Logging Level"
        description: "Set the logging level"
        type: "string"
        default: "INFO"
      expression:
        title: "Expression"
        description: "Set the content of the body"
        type: "string"
        default: "${body}"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
  dependencies:
  - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeConfigurationId}}"
      from:
        uri: "{{in}}"
        steps:
          - log:
              logName: "org.assimbly.runtime.{{flowId}}"
              logLanguage: "{{language}}"
              loggingLevel: "{{loggingLevel}}"
              message: "{{expression}}"
          - to:
              uri: "{{out}}"
