apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: manageflow-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "manageflow sink"
    description: |-
      to do
    type: object
    properties:
      path:
        title: Path
        description: Path
        type: string
      action:
        title: Path
        description: Path
        type: string
        default: "startflow"
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setProperty:
              name: flowId
              constant: "{{path}}"
          - setProperty:
              name: action
              constant: "{{action}}"
          - process:
              ref: "ManageFlowProcessor"