apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "openai-action"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "OpenAI Action"
    type: "object"
    properties:
      operation:
        type: "string"
        default: "chat-completion"
      apiKey:
        type: "string"
        format: "password"
      model:
        type: "string"
        default: "gpt-4o-mini"
      in:
        type: "string"
        default: "kamelet:source"
      out:
        type: "string"
        default: "kamelet:sink"
      stepId:
        type: "string"
      routeId:
        type: "string"
      routeConfigurationId:
        type: "string"
        default: "0"
  dependencies:
    - "camel:kamelet"
    - "camel:openai"
  template:
    route:
      routeConfigurationId: "{{routeConfigurationId}}"
      from:
        uri: "{{in}}"
        steps:
          - convertBodyTo:
              type: String
          - setHeader:
              name: "CamelOpenAIUserMessage"
              constant: "maak een grapje"
          - to:
              uri: "openai:{{operation}}"
              parameters:
                apiKey: "{{apiKey}}"
                model: "{{model}}"
          - to:
              uri: "{{out}}"
