apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: options-source
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "options source"
    description: |-
      to do
    type: object
    properties:
      path:
        title:
        description: .
        type: string
      options:
        title:
        description: .
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "rest:options:{{path}}?{{options}}"
        steps:
          - to:
              uri: "kamelet:sink"