apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: pdftotext-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "pdf to text sink"
    description: |-
      PDF to text in message
    type: object
    properties:
      options:
        title: Options
        description: Options
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "pdftotext:path"