apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "pollenrich-sink"
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "pollenrich sink"
    description: "Enrich message by polling"
    type: "object"
    properties:
      path:
        title: "Path"
        description: "Path"
        type: "string"
      options:
        title: "Options"
        description: "Options"
        type: "string"
      timeout:
        title: "Time Out"
        description: "Time Out"
        type: "string"
        default: "60000"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeId:
        title: "Route ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
  dependencies:
  - "camel:kamelet"
  template:
    route:
      from:
        uri: "{{in}}"
        steps:
        - step:
            id: "{{routeId}}"
            steps:
            - pollEnrich:
                expression:
                  simple:
                    expression: "{{path}}?{{options}}"
                timeout: "{{timeout}}"
      routeConfigurationId: "{{routeConfigurationId}}"
