apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: pollenrich-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "pollenrich action"
    description: |-
      Enrich message by polling
    type: object
    properties:
      path:
          title: Path
          description: Path
          type: string
      options:
          title: Options
          description: Options
          type: string
      timeout:
        title: Time Out
        description: Time Out
        type: string
        default: "60000"
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - pollEnrich:
              timeout: "{{timeout}}"
              simple:
                expression: "{{path}}?{{options}}"
          - to:
              uri: "kamelet:sink"