apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: prependtobody-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "prependtobody action"
    description: |-
      Prepend to message body
    type: object
    properties:
      path:
          title: Path
          description: Path
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - transform:
              method: body().append("{{path}}")
          - to:
              uri: "kamelet:sink"