apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: print-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "print action"
    description: |-
      Prints message to the console
    type: object
    properties:
      path:
          title: Path
          description: Path
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - log: "{{path}}"
          - to:
              uri: "kamelet:sink"