apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: python-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "python action"
    description: |-
      Apply Python script
    type: object
    properties:
      path:
          title: Path
          description: Path
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setBody:
              python: "{{path}}"
          - to:
              uri: "kamelet:sink"