apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: python-script
  labels:
    camel.apache.org/kamelet.type: "script"
spec:
  definition:
    title: "python script"
    description: |-
      Apply Python script
    type: object
    properties:
      path:
        title: Path
        description: Path
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setBody:
              python: "{{path}}"
          - to:
              uri: "kamelet:sink"