apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: python-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "python sink"
    description: |-
      Apply Python script
    type: object
    properties:
      path:
        title: Path
        description: Path
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setBody:
              python: "{{path}}"