apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "queue-async-action"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "queue async action"
    description: "Links messages to another flow (outbound) using a queue like activemq asynchronously"
    type: "object"
    properties:
      transport:
        title: "Transport"
        description: "Transport"
        type: "string"
        default: "activemq"
      targetQueueId:
        title: "targetQueueId"
        description: "Queue ID of the target flow"
        type: "string"
      connectionFactory:
        title: "Connection Factory"
        description: "Connection Factory to ActiveMQ"
        type: "string"
      exchangePattern:
        title: "Exchange Pattern"
        description: "Exchange Pattern: InOnly or InOut"
        type: "string"
        default: "InOut"
      timeToLive:
        title: "TimeToLive"
        description: "Time in milliseconds that a message stays on the queue when it's not consumed"
        type: "integer"
        default: "86400000"
      requestTimeout:
        title: "Request Timeout"
        description: "Timeout in milliseconds that is waited until a reply arrives"
        type: "integer"
        default: "20000"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "mock:sink"
      sink:
        title: "Sink"
        type: "boolean"
        default: false
      routeId:
        title: "Route ID"
        type: "string"
      stepId:
        title: "Step ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
  dependencies:
  - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeConfigurationId}}"
      from:
        uri: "{{in}}"
        steps:
        - step:
            id: "step-{{stepId}}"
            steps:
            - toD:
                uri: "{{transport}}:{{targetQueueId}}?connectionFactory={{connectionFactory}}&exchangePattern={{exchangePattern}}&synchronous=false&timeToLive={{timeToLive}}&requestTimeout={{requestTimeout}}"
            - to:
                disabled: "{{sink}}"
                uri: "{{out}}"