apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "queue-action"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "queue action"
    description: "Links messages to another flow (outbound) using a queue like activemq"
    type: "object"
    properties:
      transport:
        title: "Transport"
        description: "Transport"
        type: "string"
        default: "activemq"
      targetQueueId:
        title: "targetQueueId"
        description: "Queue ID of the target flow"
        type: "string"
      connectionFactory:
        title: "Connection Factory"
        description: "Connection Factory"
        type: "string"
      exchangePattern:
        title: "Exchange Pattern"
        description: "Exchange Pattern"
        type: "string"
        default: "InOut"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "mock:sink"
      sink:
        title: "Sink"
        type: "boolean"
        default: false
      routeId:
        title: "Route ID"
        type: "string"
      stepId:
        title: "Step ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
  dependencies:
  - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeConfigurationId}}"
      from:
        uri: "{{in}}"
        steps:
        - step:
            id: "step-{{stepId}}"
            steps:
            - toD:
                uri: "{{transport}}:{{targetQueueId}}?connectionFactory=#{{connectionFactory}}&exchangePattern={{exchangePattern}}&synchronous=true"
            - to:
                disabled: "{{sink}}"
                uri: "{{out}}"