apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: queuethrottle-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "queuethrottle action"
    description: |-
      Throttles messages on an ActiveMQ queue
    type: object
    properties:
      timePeriod:
          title: Time Period
          description: Time Period
          type: string
          default: 5000
      messages:
          title: Messages
          description: Max number of messages
          type: string
          default: 1
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - throttle:
              asyncDelayed: true
              timePeriodMillis: "{{timePeriod}}"
              expression:
                constant: "{{messages}}"
              correlationExpression:
                constant:
                  expression: "{{routeId}}"
          - to:
              uri: "activemq:{{routeId}}_throttling?exchangePattern=InOnly&timeToLive=86400000"
          - to:
              uri: "kamelet:sink"