apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: rabbitmq-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "rabbitmq sink"
    description: |-
      Sends messages to RabbitMQ
    type: object
    properties:
      path:
          title: Path
          description: Path
          type: string
      options:
          title: Options
          description: Options
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setProperty:
              name: excludedHeader_breadcrumbId
              simple: "${header.breadcrumbId}"
          - removeHeader:
              name: "breadcrumbId"
          - setHeader:
              name: CamelRabbitmqDeliveryMode
              constant: "2"
          - toD:
              uri: "rabbitmq:{{path}}?{{options}}"
          - setHeader:
              name: breadcrumbId
              simple: "${exchangeProperty.excludedHeader_breadcrumbId}"
          - removeProperty:
              name: "excludedHeader_breadcrumbId"