apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: rabbitmq-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "rabbitmq action"
    description: |-
      Send message to a RabbitMQ broker
    type: object
    properties:
      path:
        title: path
        description: path
        type: string
        default: default
      connectionFactory:
        title: connectionFactory
        description: The connectionFactory
        type: string
      exchangeType:
        title: exchangeType
        description: exchangeType
        type: string
      routingKey:
        title: routingKey
        description: The routing key
        type: string
      queues:
        title: Queues
        description: Queues
        type: string
      durable:
        title: Durable
        description: Durable
        type: boolean
        default: false
      autoDelete:
        title: AutoDelete
        description: AutoDelete
        type: boolean
        default: false
      useErrorRoute:
        title: useErrorRoute
        description: useErrorRoute
        type: boolean
        default: false
      autoDeclareProducer:
        title: Auto Declare Producer
        description: Specifies whether the producer should auto declare binding between exchange, queue and routing key when starting
        type: boolean
        default: true
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "spring-rabbitmq:{{path}}?connectionFactory={{connectionFactory}}&exchangeType={{exchangeType}}&routingKey=RAW({{?routingKey}})&queues=RAW({{?queues}})&arg.queue.durable={{durable}}&arg.queue.autoDelete={{autoDelete}}&bridgeErrorHandler={{useErrorRoute}}&autoDeclareProducer={{autoDeclareProducer}}"
          - to:
              uri: "kamelet:sink"