apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: rabbitmq-sink
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "rabbitmq sink"
    description: |-
      Send message to a RabbitMQ broker
    type: object
    properties:
      path:
        title: path
        description: path
        type: string
      connectionFactory:
        title: connectionFactory
        description: The connectionFactory
        type: string
      exchangeType:
        title: exchangeType
        description: exchangeType
        type: string
      queues:
        title: Queues
        description: Queues
        type: string
      durable:
        title: Durable
        description: Durable
        type: boolean
        default: false
      autoDelete:
        title: AutoDelete
        description: AutoDelete
        type: boolean
        default: false
      useErrorRoute:
        title: useErrorRoute
        description: useErrorRoute
        type: boolean
        default: false
      exchangePattern:
        title: ExchangePattern
        description: ExchangePattern
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - toD:
              uri: "spring-rabbitmq:{{path}}?connectionFactory={{connectionFactory}}&exchangeType={{exchangeType}}&queues=RAW({{?queues}})&arg.queue.durable={{durable}}&arg.queue.autoDelete={{autoDelete}}&bridgeErrorHandler={{useErrorRoute}}&exchangePattern={{exchangePattern}}"