apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: rabbitmq-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "rabbitmq action"
    description: |-
      Sends messages to RabbitMQ
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
        title: Path
        description: Path
        type: string
      options:
        title: Options
        description: Options
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - setProperty:
              name: excludedHeader_breadcrumbId
              simple: "${header.breadcrumbId}"
          - removeHeader:
              name: "breadcrumbId"
          - setHeader:
              name: CamelRabbitmqDeliveryMode
              constant: "2"
          - toD:
              uri: "rabbitmq:{{path}}?{{options}}"
          - setHeader:
              name: breadcrumbId
              simple: "${exchangeProperty.excludedHeader_breadcrumbId}"
          - removeProperty:
              name: "excludedHeader_breadcrumbId"
          - to:
              uri: "kamelet:sink"