apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: recipient-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "recipient action"
    description: |-
      Sends a copy of the message to the recipient (use the recipient router when using more recipients)
    type: object
    properties:
    dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "kamelet:sink"