apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: recipients-router
  labels:
    camel.apache.org/kamelet.type: "router"
spec:
  definition:
    title: "recipients router"
    description: |-
      Send message to one or more uris
    type: object
    properties:
      out_list:
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "{{out_list}}"