apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: removeheaders-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "removeheaders action"
    description: |-
      Remove headers from message
    type: object
    properties:
      pattern:
          title:
          description: Regex pattern to remove headers
          type: string
      excludePatterns:
          title: Exclude Pattern
          description: Exclude Pattern
          type: string
          default: 0
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - removeHeaders:
              pattern: "{{pattern}}"
              exclude-pattern: "{{excludePattern}}"
          - to:
              uri: "kamelet:sink"