apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "removeheaders-action"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "removeheaders action"
    description: "Removes headers from message using a pattern"
    type: "object"
    properties:
      pattern:
        title: null
        description: "Regex pattern to remove headers"
        type: "string"
      excludePatterns:
        title: "Exclude Pattern"
        description: "Exclude Pattern"
        type: "string"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeId:
        title: "Route ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
  dependencies:
  - "camel:kamelet"
  template:
    route:
      from:
        uri: "{{in}}"
        steps:
        - step:
            id: "{{routeId}}"
            steps:
            - removeHeaders:
                pattern: "{{pattern}}"
                exclude-pattern: "{{?excludePattern}}"
            - to:
                uri: "{{out}}"
      routeConfigurationId: "{{routeConfigurationId}}"
