apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: removeheaders-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "removeheaders sink"
    description: |-
      Removes headers from message using a pattern
    type: object
    properties:
      pattern:
        title:
        description: Regex pattern to remove headers
        type: string
      excludePatterns:
        title: Exclude Pattern
        description: Exclude Pattern
        type: string
        default: 0
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - removeHeaders:
              pattern: "{{pattern}}"
              exclude-pattern: "{{?excludePattern}}"