apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: replaceinpdf-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "replaceinpdf action"
    description: |-
      Replace headers in PDF
    type: object
    properties:
      path:
          title: Path
          description: Path
          type: string
      options:
          title: Options
          description: Options
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "pdf-transform://{{path}}?{{options}}"
          - to:
              uri: "kamelet:sink"