apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: rest-source
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "rest source"
    description: |-
      to do
    type: object
    properties:
      method:
        title: Method
        description: HTTP Method (GET, POST, PUT, DELETE, TRACE, OPTIONS, PATCH CONNECT)
        type: string
      path:
          title: 
          description: .
          type: string
      options:
          title: Options
          description: Endpoint options
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "rest:{{method}}:{{path}}?{{options}}"
        steps:
          - to:
              uri: "kamelet:sink"