apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: trace-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "rest action"
    description: |-
      Calls a REST Endpoint
    type: object
    properties:
      method:
        title: Method
        description: HTTP Method (GET, POST, PUT, DELETE, TRACE,OPTIONS, PATCH, CONNECT)
        type: string
      path:
        title: Path
        description: Path
        type: string
      options:
        title: Options
        description: Endpoint options
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "rest:{{method}}:{{path}}?{{options}}"