apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: setbodybyheader-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "setbodybyheader action"
    description: |-
      Set body from a header
    type: object
    properties:
      path:
          title: Path
          description: Path
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setBody:
              header: "{{path}}"
          - to:
              uri: "kamelet:sink"