apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: setbodyasonline-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "setbodyasonline action"
    description: |-
      Converts the body to a String and removes all line-breaks so the string is in one line.
    type: object
    properties:
      path:
          title: Path
          description: Path
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setBody:
              simple: "${bodyOneLine}"
          - to:
              uri: "kamelet:sink"