apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "setbodybyheader-action"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "setbodybyheader action"
    description: "Set body from a header"
    type: "object"
    properties:
      headerName:
        title: "HeaderName"
        description: "Name of the header"
        type: "string"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeId:
        title: "Route ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
  dependencies:
  - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeConfigurationId}}"
      from:
        uri: "{{in}}"
        steps:
        - step:
            id: "{{routeId}}"
            steps:
            - setBody:
                header: "{{headerName}}"
            - to:
                uri: "{{out}}"