apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: setbodyasstring-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "setbodyasstring action"
    description: |-
      Set body as a string type
    type: object
    properties:
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - convertBodyTo:
              type: "java.lang.String"
          - to:
              uri: "kamelet:sink"