apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: setbody-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "setbody action"
    description: |-
      to do
    type: object
    properties:
      language:
        title: Language
        description: Set the expression language
        type: string
        default: constant
      content:
        title: Content
        description: Set the content of the body
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setBody:
              language: "{{language}}"
              expression: "{{content}}"