apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: setbodyasonline-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "setbodyasonline sink"
    description: |-
      Converts the body to a String and removes all line-breaks so the string is in one line.
    type: object
    properties:
      path:
          title: Path
          description: Path
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setBody:
              simple: "${bodyOneLine}"