apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: setbody-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "setbody action"
    description: |-
      to do
    type: object
    properties:
      language:
        title: Language
        description: Set the expression language
        type: string
        default: constant
      expression:
        title: Expression
        description: Set the content of the body
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setBody:
              language:
                language: "{{language}}"
                expression: "{{expression}}"
          - to:
              uri: "kamelet:sink"