apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: setbody-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "setbody sink"
    description: |-
      to do
    type: object
    properties:
      expressionType:
        title: Expression Type
        description: Set the expression language
        type: string
        default: constant
      content:
        title: Content
        description: Set the content of the body
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setProperty:
              name: assimbly.body
              constant: "{{content}}"
          - setProperty:
              name: assimbly.language
              constant: "{{expressionType}}"
          - process:
              ref: "SetBodyProcessor"