apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: setheaders-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "setmessage action"
    description: |-
      Set headers on a message
    type: object
    properties:
      headers:
        title: Headers
        description: Headers
        type: string
        default: 0
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setProperty:
              name: assimbly.headers
              constant: "{{headers}}"
          - process:
              ref: "SetHeadersProcessor"
          - to:
              uri: "kamelet:sink"