apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "setheaderbybody-action"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "setbodybyheader action"
    description: "Set header from body"
    type: "object"
    properties:
      path:
        title: "Path"
        description: "Path"
        type: "string"
        default: "body"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeId:
        title: "Route ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
  dependencies:
  - "camel:kamelet"
  template:
    route:
      from:
        uri: "{{in}}"
        steps:
        - step:
            id: "{{routeId}}"
            steps:
            - setHeader:
                name: "{{path}}"
                simple: "${body}"
            - to:
                uri: "{{out}}"
      routeConfigurationId: "{{routeConfigurationId}}"
