apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: setheader-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "setheader action"
    description: |-
      Set an exchange header
    type: object
    properties:
      path:
        title: Path
        description: Path
        type: string
      value:
        title: Value
        description: Value of header
        type: string
      language:
        title: Language
        description: Expression language to evaluate
        type: string
        default: constant
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - choice:
              when:
                - simple: "'{{language}}' == 'simple'"
                  steps:
                  - setHeader:
                      name: "{{path}}"
                      simple: "{{value}}"
                - simple: "'{{language}}' == 'xpath'"
                  steps:
                  - setHeader:
                      name: "{{path}}"
                      xpath: "{{value}}"
                - simple: "'{{language}}' == 'jsonpath'"
                  steps:
                  - setHeader:
                      name: "{{path}}"
                      jsonpath: "{{value}}"
                - simple: "'{{language}}' == 'groovy'"
                  steps:
                  - setHeader:
                      name: "{{path}}"
                      groovy: "{{value}}"
              otherwise:
                steps:
                  - setHeader:
                      name: "{{path}}"
                      constant: "{{value}}"
          - to:
              uri: "kamelet:sink"