apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: setoriginalbody-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "setoriginalbody sink"
    description: |-
      Sets the original body of a exchange
    type: object
    properties:
      path:
          title: Path
          description: Path
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setBody:
              simple: "${originalBody}"