apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: setoauth2token-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "setoauth2token action"
    description: |-
      Set oAuth2token
    type: object
    properties:
      path:
        title: path
        description: path of the URI (id)
        type: string
        default: dummy
      options:
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "oauth2token://{{path}}?{{options}}"
          - to:
              uri: "kamelet:sink"