apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: setproperty-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "setproperty sink"
    description: |-
      Set an exchange property
    type: object
    properties:
      path:
        title: Path
        description: Path
        type: string
      value:
        title: Value
        description: Value of property
        type: string
      language:
        title: Language
        description: Expression language to evaluate
        type: string
        default: constant
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - choice:
              when:
                - simple: "'{{language}}' == 'simple'"
                  steps:
                    - setProperty:
                        name: "{{path}}"
                        simple: "{{value}}"
                - simple: "'{{language}}' == 'xpath'"
                  steps:
                    - setProperty:
                        name: "{{path}}"
                        xpath: "{{value}}"
                - simple: "'{{language}}' == 'jsonpath'"
                  steps:
                    - setProperty:
                        name: "{{path}}"
                        jsonpath: "{{value}}"
                - simple: "'{{language}}' == 'groovy'"
                  steps:
                    - setProperty:
                        name: "{{path}}"
                        groovy: "{{value}}"
              otherwise:
                steps:
                  - setProperty:
                      name: "{{path}}"
                      constant: "{{value}}"