apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: setrequestreply-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "setrequestreply action"
    description: |-
      Set the exchange pattern to inOut (request and reply)
    type: object
    properties:
  dependencies:
      - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setExchangePattern: "InOut"
          - to:
              uri: "kamelet:sink"