apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "setuuid-action"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "setuuid action"
    description: "Set UUID as message header"
    type: "object"
    properties:
      headerName:
        title: "HeaderName"
        description: "Name of the header"
        type: "string"
        default: "UUID"
      generator:
        title: "Generator"
        description: "Type of UUID Generator"
        type: "string"
        default: "default"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeId:
        title: "Route ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
  dependencies:
  - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeConfigurationId}}"
      from:
        uri: "{{in}}"
        steps:
        - step:
            id: "{{routeId}}"
            steps:
            - setHeader:
                name: "{{headerName}}"
                simple: "${uuid({{generator}})}"
            - to:
                uri: "{{out}}"
