apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: sftpenrich-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "sftp enrich action"
    description: |-
      Enrich a file from a SFTP directory
    type: object
    properties:
      path:
        title: path
        description: path
        type: string
      options:
        title: options
        description: options
        type: string
      timeout:
        title: Time Out
        description: Time Out
        type: string
        default: "10000"
      maxMessagesPerPoll:
        title: MaxMessagesPerPoll
        description: Maximum Messages to pick up per poll
        type: string
        default: "1"
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setProperty:
              name: Enrich-Type
              constant: "application/override"
          - setProperty:
              name: Enrich-MaxMessagesPerPoll
              constant: "1"
          - loop:
              doWhile: true
              expression:
                simple: "${exchangeProperty.Enrich-MaxMessagesPerPoll} != 0"
              steps:
                - pollEnrich:
                    timeout: "{{timeout}}"
                    aggregationStrategy: "#CurrentEnrichStrategy"
                    simple:
                      expression: "sftp:{{path}}?{{?options}}&throwExceptionOnConnectFailed=true&bridgeErrorHandler=true&serverHostKeys=ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa&publicKeyAcceptedAlgorithms=ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa&keyExchangeProtocols=curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1"
                - setProperty:
                    name: Enrich-MaxMessagesPerPoll
                    simple: "${exchangeProperty.Enrich-MaxMessagesPerPoll}--"
                - choice:
                    when:
                      - simple: "${body} == null"
                        steps:
                          - setProperty:
                              name: Enrich-MaxMessagesPerPoll
                              constant: "0"
                - to:
                    uri: "kamelet:sink"
                - removeHeaders:
                    pattern: "CamelFile*"
                - setProperty:
                    name: Enrich-Response
                    simple: "${body}"
          - setBody:
              simple: "${exchangeProperty.Enrich-Response}"
