apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: sftp-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "sftp action"
    description: |-
      Send message to SFTP directory
    type: object
    properties:
      scheme:
          title: scheme of components
          description: Endpoint URI
          type: string
      path:
        title: path
        description: path of component
        type: string
        default: dummy
      options:
        title: options (query parameterS)
        description: Endpoint URI
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - toD:
              uri: "{{scheme}}://{{path}}?{{options}}"
          - to:
              uri: "kamelet:sink"