apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: sftp-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "sftp sink"
    description: |-
      Send message to SFTP directory
    type: object
    properties:
      path:
        title: path
        description: path of component
        type: string
        default: dummy
      options:
        title: options (query parameterS)
        description: Endpoint URI
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - toD:
              uri: "sftp:{{path}}?{{?options}}"