apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: simplereplace-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "simplereplace sink"
    description: |-
      Replace simple expression in the message body
    type: object
    properties:
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "dataformat:simple-replace:unmarshal"