apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "simple-script"
  labels:
    camel.apache.org/kamelet.type: "script"
spec:
  definition:
    title: "simple script"
    description: "Applies simple expression to message body"
    type: "object"
    properties:
      path:
        title: "Path"
        description: "Path"
        type: "string"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeId:
        title: "Route ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
  dependencies:
  - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
        - step:
            id: "{{routeId}}"
            steps:
            - setBody:
                simple: "{{path}}"
            - to:
                uri: "kamelet:sink"
      routeConfigurationId: "{{routeConfigurationId}}"
