apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: simple-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "simple sink"
    description: |-
      Applies simple expression to message body
    type: object
    properties:
      path:
          title: Path
          description: Path
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - setBody:
              simple: "{{path}}"