apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: simplereplace-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "simplereplace action"
    description: |-
      Replace simple expression in the message body
    type: object
    properties:
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "dataformat:simple-replace:unmarshal"
          - to:
              uri: "kamelet:sink"