apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: simple-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "simple sink"
    description: |-
      Applies simple expression to message body
    type: object
    properties:
      routeconfiguration_id:
        type: string
        default: "0"
      path:
          title: Path
          description: Path
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      route-configuration-id: "{{routeconfiguration_id}}"
      from:
        uri: "kamelet:source"
        steps:
          - set-body:
              simple: "{{path}}"