apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: smb-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "smb sink"
    description: |-
      Send messages to a SMB directory
    type: object
    properties:
      path:
        title: path
        description: path of component
        type: string
      options:
        title: options (query parameterS)
        description: Endpoint URI
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - toD:
              uri: "smb:{{path}}?{{?options}}"