apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: smtp-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "smtp action"
    description: |-
      SMTP (Simple Mail Transfer Protocol) SMTP is the standard protocol for sending emails from one system to another.
    type: object
    properties:
      scheme:
          title: scheme of components
          description: Endpoint URI
          type: string
      path:
        title: path
        description: path of component
        type: string
        default: dummy
      username:
        title: username smpt server
        description: username smpt server
        type: string
        x-descriptors:
          - urn:camel:group:credentials
      password:
        title: password of smtp server
        description: password of smtp server
        type: string
        x-descriptors:
          - urn:camel:group:credentials
      from:
        title: from email address
        description: from email address
        type: string
      subject:
        title: subject of email
        description: subject of email
        type: string
      to:
        title: to email address
        description: to email address
        type: string
      replyTo:
        title: replyTo email address
        description: replyTo email address
        type: string
      tenant:
        title: tenant email address
        description: tenant email address
        type: string
      accessToken:
        title: AccessToken
        description: Access token
        type: string
      authenticationType:
        title: AthenticationType
        description: Which authentication type is used (like oauth)
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    beans:
      - name: ExtendedHeaderFilterStrategy
        type: "#class:org.assimbly.util.mail.ExtendedHeaderFilterStrategy"
    route:
      from:
        uri: "kamelet:source"
        steps:
          - toD:
              uri: "{{scheme}}://{{path}}?accessToken=RAW({{?accessToken}})&authenticationType=RAW({{?authenticationType}})&username=RAW({{username}})&password=RAW({{password}})&from=RAW({{from}})&subject=RAW({{subject}})&to=RAW({{to}})&replyTo=RAW({{replyTo}})&tenant=RAW({{tenant}})&mail.smtp.starttls.enable=true&headerFilterStrategy=#{{ExtendedHeaderFilterStrategy}}"
          - to:
              uri: "kamelet:sink"