apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "smtp-action"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "smtp action"
    description: "SMTP (Simple Mail Transfer Protocol) SMTP is the standard protocol\
      \ for sending emails from one system to another."
    type: "object"
    properties:
      scheme:
        title: "scheme of components"
        description: "Endpoint URI"
        type: "string"
      path:
        title: "path"
        description: "path of component"
        type: "string"
        default: "dummy"
      username:
        title: "username smpt server"
        description: "username smpt server"
        type: "string"
        x-descriptors:
        - "urn:camel:group:credentials"
      password:
        title: "password of smtp server"
        description: "password of smtp server"
        type: "string"
        x-descriptors:
        - "urn:camel:group:credentials"
      from:
        title: "from email address"
        description: "from email address"
        type: "string"
      subject:
        title: "subject of email"
        description: "subject of email"
        type: "string"
      to:
        title: "to email address"
        description: "to email address"
        type: "string"
      replyTo:
        title: "replyTo email address"
        description: "replyTo email address"
        type: "string"
      tenantDbName:
        title: "TenantDbName"
        description: "tenant db name"
        type: "string"
      accessToken:
        title: "AccessToken"
        description: "Access token"
        type: "string"
      authenticationType:
        title: "AthenticationType"
        description: "Which authentication type is used (like oauth)"
        type: "string"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeId:
        title: "Route ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
  dependencies:
  - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeConfigurationId}}"
      from:
        uri: "{{in}}"
        steps:
        - step:
            id: "{{routeId}}"
            steps:
            - toD:
                uri: "{{scheme}}:{{path}}"
                parameters:
                  username: "RAW({{username}})"
                  password: "RAW({{?password}})"
                  accessToken: "RAW({{?accessToken}})"
                  from: "RAW({{?from}})"
                  to: "RAW({{to}})"
                  replyTo: "RAW({{?replyTo}})"
                  subject: "RAW({{subject}})"
                  authenticationType: "RAW({{?authenticationType}})"
                  tenantDbName: "RAW({{?tenantDbName}})"
                  mail.smtp.starttls.enable: true
            - to:
                uri: "{{out}}"
