apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "soap-sink"
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "soap sink"
    description: "Sends SOAP Requests"
    type: "object"
    properties:
      uri:
        title: "URI"
        description: "Endpoint URI"
        type: "string"
      action:
        title: "Action"
        description: "SOAP Action"
        type: "string"
      extract:
        title: "Extract"
        description: "Extracts the SOAP envelope"
        type: "String"
      smart:
        title: "Smart"
        description: "Apply namespace automatically"
        type: "String"
      params:
        title: "Params"
        description: "Query parameters on the SOAP URL"
        type: "string"
      auth:
        title: "Auth"
        description: "Authentication (optional)"
        type: "string"
      headers:
        title: "Headers"
        description: "SOAP headers (optional)"
        type: "string"
      httpHeaders:
        title: "HTTPHeaders"
        description: "HTTP Headers (optional)"
        type: "string"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeId:
        title: "Route ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
  dependencies:
  - "camel:kamelet"
  template:
    route:
      routeConfigurationId: "{{routeConfigurationId}}"
      from:
        uri: "{{in}}"
        steps:
        - step:
            id: "{{routeId}}"
            steps:
            - to:
                uri: "soap://{{path}}?action={{action}}&extract={{extract}}&smart={{smart}}&params={{?params}}&auth={{?auth}}&headers={{?headers}}&httpHeaders={{?httpHeaders}}"