apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: split-router
  labels:
    camel.apache.org/kamelet.type: "router"
spec:
  definition:
    title: "split-router"
    description: |-
      Splits message by xpath
    type: object
    properties:
      path:
          title: Path
          description: Path
          type: string
      language:
        title: Language
        description: Language
        type: string
      expression:
          title: Expression
          description: Expression
          type: string
      out_rule:
        title: Out Rule
        description: Out Rule
        type: string
      out_default:
        title: Out Default Rule
        description: Out Default Rule
        type: string
        default: "mock:0"
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - split:
              language:
                language: "{{language}}"
                expression: "{{expression}}"
              steps:
                - setHeader:
                    name: CamelSplitIndex
                    simple: "${exchangeProperty.CamelSplitIndex}"
                - setHeader:
                    name: CamelSplitSize
                    simple: "${exchangeProperty.CamelSplitSize}"
                - setHeader:
                    name: CamelSplitComplete
                    simple: "${exchangeProperty.CamelSplitComplete.toString().trim()}"
                - to: "{{out_rule}}"
          - to:
              uri: "{{out_default}}"