apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: spring-rabbitmq-source
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "rabbitmq source"
    description: |-
      Receives messages from RabbitMQ
    type: object
    properties:
      path:
          title: Path
          description: Path
          type: string
      options:
          title: Options
          description: Options
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "rabbitmq:{{path}}?{{options}}"
        steps:
          - to:
              uri: "kamelet:sink"