apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "springai-chat-action"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "springai-chat action"
    description: "chat component for springai"
    type: "object"
    properties:
      path:
        title: "Path"
        description: "Path"
        type: "string"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeId:
        title: "Route ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
      apiKey:
        title: "API Key"
        type: "string"
        default: "insertapikeyhere"
      modelName:
        title: "Model Name"
        type: "string"
        default: "gemini-3-flash-preview"
      prompt:
        title: "Prompt"
        type: "string"
        default: "Vertel me een leuke grap over programmeurs."
  dependencies:
    - "camel:kamelet"
  template:
    beans:
      - name: "springChatModel"
        type: "#class:org.assimbly.dil.blocks.models.GoogleAiGeminiChatModel"
        factoryMethod: "create"
    route:
      from:
        uri: "{{in}}"
        steps:
          - convertBodyTo:
              type: String
          - setHeader:
              name: "SpringaiChatPromptTemplate"
              expression:
                constant:
                  expression: "maak een grapje"
          - to:
              uri: "log:springaiin?showAll=true&multiline=true"
          - to:
              #              uri: "langchain4j-chat://{{routeId}}?chatModel=#bean:geminiChatModel"
              uri: "spring-ai-chat://{{routeId}}?chatModel=#bean:springChatModel"
          - to:
              uri: "log:springaiout?showAll=true&multiline=true"
          - to:
              uri: "{{out}}"

