apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: texttobase64-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "texttobase64 sink"
    description: |-
      Convert text to base64 string
    type: object
    properties:
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - marshal:
              base64: {}