apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: univocity-csv-sink
  labels:
    camel.apache.org/kamelet.type: "csv-sink"
spec:
  definition:
    title: "univocity csv-sink"
    description: |-
      to do
    type: object
    properties:
      path:
        title: Path
        description: Path
        type: string
      options:
        title: Path
        description: Path
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "dataformat:univocityCsv:{{path}}?{{options}}"