apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "univocity-csv-action"
  labels:
    camel.apache.org/kamelet.type: "csv-action"
spec:
  definition:
    title: "univocity csv-action"
    description: "to do"
    type: "object"
    properties:
      path:
        title: "Path"
        description: "Path"
        type: "string"
      options:
        title: "Path"
        description: "Path"
        type: "string"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeId:
        title: "Route ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
  dependencies:
  - "camel:kamelet"
  template:
    route:
      from:
        uri: "{{in}}"
        steps:
        - step:
            id: "{{routeId}}"
            steps:
            - to:
                uri: "dataformat:univocityCsv:{{path}}?{{options}}"
            - to:
                uri: "{{out}}"
      routeConfigurationId: "{{routeConfigurationId}}"
