apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: unzip-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "unzip action"
    description: |-
      Unzips a message
    type: object
    properties:
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - process:
              ref: "Unzip"
          - to:
              uri: "kamelet:sink"