apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "velocity-action"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "velocity action"
    description: "Send messages to a directory"
    type: "object"
    properties:
      path:
        title: "path"
        description: "path of component (reference id to the registry)"
        type: "string"
        default: "dummy"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeId:
        title: "Route ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
  dependencies:
  - "camel:kamelet"
  template:
    route:
      from:
        uri: "{{in}}"
        steps:
        - step:
            id: "{{routeId}}"
            steps:
            - to:
                uri: "velocity:{{path}}"
            - to:
                uri: "{{out}}"
      routeConfigurationId: "{{routeConfigurationId}}"
