apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: wiretap-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "wiretap sink"
    description: |-
      Copy the original in a fire and forget style
    type: object
    properties:
      path:
          title: Path
          description: Path
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - wireTap:
              uri: "{{path}}"
              executor-service: "wiretapProfile"