apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: wiretap-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "wiretap action"
    description: |-
      Copy the original in a fire and forget style
    type: object
    properties:
      path:
          title: Path
          description: Path
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - wireTap:
              uri: "{{path}}"
              executor-service: "wiretapProfile"
          - to:
              uri: "kamelet:sink"