apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: xmltocsv-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "xmltocsv action"
    description: |-
      Transform XML to CSV
    type: object
    properties:
      options:
        title: options
        description: Options
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "xmltocsv://?{{options}}"
          - to:
              uri: "kamelet:sink"