apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: xmltoexcel-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "xmltoexcel sink"
    description: |-
      Converts XML to Excel
    type: object
    properties:
      includeHeader:
        title: Include Header
        description: .
        type: string
        default: true
      includeIndexColumn:
        title: Include Index Column
        description: .
        type: string
        default: false
      indexColumnName:
        title: Index ColumnName
        description: .
        type: string
        default: line
      orderHeaders:
        title: Order Headers
        description: .
        type: string
        default: UNORDERED
      excelFormat:
        title: Excel Format
        description: .
        type: string
        default: XLSX
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "xmltoexcel://?includeHeader={{includeHeader}}&includeIndexColumn={{includeIndexColumn}}&indexColumnName={{indexColumnName}}&orderHeaders={{orderHeaders}}&excelFormat={{excelFormat}}"