apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: xmltoexcel-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "xmltoexcel action"
    description: |-
      Converts XML to Excel
    type: object
    properties:
      includeHeader:
        title: Include Header
        description: Whether to include a header row in the Excel output
        type: string
        default: true
      includeIndexColumn:
        title: Include Index Column
        description: Whether to include an index column in the Excel output
        type: string
        default: false
      indexColumnName:
        title: Index ColumnName
        description: The name of the index column
        type: string
        default: line
      orderHeaders:
          title: Order Headers
          description:  how the columns should be ordered in the Excel document (by name). unordered, ascending, or descending
          type: string
          default: unordered
      excelFormat:
          title: Excel Format
          description: Choose between Excel format xslx or xsl
          type: string
          default: xlsx
      expressions:
        title: Worksheet expressions
        description: Custom Worksheet expressions
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "xmltoexcel://?includeHeader={{includeHeader}}&includeIndexColumn={{includeIndexColumn}}&indexColumnName={{indexColumnName}}&orderHeaders={{orderHeaders}}&excelFormat={{excelFormat}}&worksheets={{?expressions}}"
          - to:
              uri: "kamelet:sink"