apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: xmltoedifact-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "xmltoedifact sink"
    description: |-
      Converts XML to Edifact
    type: object
    properties:
      options:
        title: options
        description: Options
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "dataformat:edifact:unmarshal?{{options}}"