apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: xmltojsonsimple-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "xmltojsonsimple sink"
    description: |-
      Convert XML to JSON
    type: object
    properties:
      options:
          title: options
          description: Options
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "dataformat:custom-xmljson:marshal?{{options}}"