apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: xmltoedifactstandards-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "xmltoedifactstandards action"
    description: |-
      Convert XML to EDI (Standards)
    type: object
    properties:
      path:
          title: path
          description: Path
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "edifact-standards:{{path}}"
          - to:
              uri: "kamelet:sink"