apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: xmltoedi-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "xmltoedi sink"
    description: |-
      Converts XML to EDI
    type: object
    properties:
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "dataformat:edi:unmarshal"