apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: xslt-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "xslt sink"
    description: |-
      Apply XSLT on message
    type: object
    properties:
      path:
        title: Path
        description: Path
        type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "xslt-saxon:{{path}}?saxonExtensionFunctions=#uuid-function"