apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: xslt-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "xslt action"
    description: |-
      Apply XSLT on message
    type: object
    properties:
      path:
          title: Path
          description: Path
          type: string
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - to:
              uri: "xslt-saxon:{{path}}?saxonExtensionFunctions=#uuid-function"
          - to:
              uri: "kamelet:sink"