apiVersion: "camel.apache.org/v1"
kind: "Kamelet"
metadata:
  name: "xslt-script"
  labels:
    camel.apache.org/kamelet.type: "script"
spec:
  definition:
    title: "xslt script"
    description: "Apply XSLT on message"
    type: "object"
    properties:
      path:
        title: "Path"
        description: "Path"
        type: "string"
      in:
        title: "Source Endpoint"
        type: "string"
        default: "kamelet:source"
      out:
        title: "Sink Endpoint"
        type: "string"
        default: "kamelet:sink"
      routeId:
        title: "Route ID"
        type: "string"
      routeConfigurationId:
        title: "Route Configuration ID"
        type: "string"
        default: "0"
  dependencies:
  - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
        - step:
            id: "{{routeId}}"
            steps:
            - to:
                uri: "xslt-saxon:{{path}}?saxonExtensionFunctions=#uuid-function"
            - to:
                uri: "kamelet:sink"
      routeConfigurationId: "{{routeConfigurationId}}"
