apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: zip-action
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "zip action"
    description: |-
      Zips a message
    type: object
    properties:
  dependencies:
    - "camel:kamelet"
  template:
    route:
      from:
        uri: "kamelet:source"
        steps:
          - marshal:
              zipFile:
                id: zipFile-{{routeid}}
          - to:
              uri: "kamelet:sink"